json.image_url @gallery_image.image.url
json.lower_url api_v1_gallery_images_lower_url(@gallery_image)
json.higher_url api_v1_gallery_images_higher_url(@gallery_image)
json.destroy_url api_v1_gallery_images_destroy_url(@gallery_image)