# config/database.yml

default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: adc2024_rails_playground_09_dev

test:
  <<: *default
  database: adc2024_rails_playground_09_test

production:
  <<: *default
  database: adc2024_rails_playground_09
